pipeline{
   agent any 
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage("maven"){
        steps{ 
        sh 'mvn clean'
        sh 'mvn validate'
        sh 'mvn compile' 
        sh 'mvn install' 
        sh 'mvn test'
        sh 'mvn package'
        }
    }
    stage('upload artifact'){
        steps{
        sh 'curl -uadmin:APPrXaxbjjxRxtvSeVLxsnPmfv -T \
       target/bio*.jar \
        "http://3.88.231.28:8081/artifactory/geo-solution/geo/bio_${BUILD_ID}.jar"'
        }
    }
   } 
}

