pipeline{
   agent any 
   tools{
    maven 'M2_HOME'
   }
   stages{
    stage('sonar scan'){
        steps{
            withSonarQubeEnv('SonarQube'){
            sh 'mvn verify org.sonarsource.scanner.maven:sonar-maven-plugin:sonar \
            -Dsonar.projectKey=samamet2012_geo-app'
            }
            
        }
    }
    stage("maven1"){
        steps{ 
        sh 'mvn clean'
        sh 'mvn validate'
        sh 'mvn compile' 
        sh 'mvn install' 
        sh 'mvn test'
        sh 'mvn package'
        }
    }
    stage('upload artifact'){
        steps{
        sh 'curl -uadmin:APPrXaxbjjxRxtvSeVLxsnPmfv -T \
       target/bio*.jar \
        "http://3.88.231.28:8081/artifactory/geo-solution/geo/bio_${BUILD_ID}.jar"'
        }
    }
    stage('docker login details'){
        steps{
            sh 'aws ecr get-login-password \
            --region us-east-1 | docker login \
            --username AWS --password-stdin \
            976887127912.dkr.ecr.us-east-1.amazonaws.com'
        }
    }
   } 
}

